### ISSUE TITLE
How to build/install?

### ISSUE THREAD

**Issue by ipacman** [ellyq/coreboot#6]
Hi Elly -- I've followed your progress on porting coreboot to your Erying ES board from the beginning (before you left reddit) and would like to install it on my board. Is there any information on how to build/flash this on a stock board? I installed the "Lightning" bios successfully back in the day but am increasingly concerned about what could be installed on this board from the manufacturer. Unfortunately, the complexity of efi bios images has kept me from pursuing this so far, but I can get the flashing hardware and give it a try once I know how to merge in your solution. I did have efi save a copy of my original image and was able to load it into a uefi editor.

**Comment by ellyq** [comment]
Hi, somehow this issue flew under my radar for a while...

I have few last tests to do, as port is in decent state in my opinion. Problem is that I damaged my test board about a month ago and didn't have time to fix it (maybe will next week) so I can't test the latest patch (addressing the code review).

Building it is pretty simple, if you have developer environment ready: 
https://doc.coreboot.org/tutorial/part1.html#download-configure-and-build-coreboot

Blobs for this board already are in upstream, so in theory all you need is to clone my tree, make coreboot toolchain, configure for this board and build it.
In `make nconfig` select:

```
Mainboard ->
Vendor: Erying
Mainboard model: Polestar G613 Pro (TGL-H)
```

```
Chipset -> 
Uncheck "Enable ACPI PM timer"
Check "Use Legacy 8254 Timer"
APIC operation mode = "X2APIC"
Include CPU microcode in CBFS (Include external microcode binary) = "blobs/mainboard/erying/tgl/cpu806D0_platC2_ver00000054_2021-05-07_PRD_B0F9E245.bin"
Add descriptor.bin file = "blobs/mainboard/erying/tgl/fd.bin"
Add Intel ME/TXE firmware = "blobs/mainboard/erying/tgl/me.bin"
```

```
Devices ->
Graphics initialization = "None"
Uncheck anything related to ASPM (if checked)
Support PCIe Resizable BARs = set to 36 bits
Check "Add a Video BIOS Table (VBT) binary to CBFS" (default path)
```

```
Generic Drivers ->
Check "Support for flash based, SMM mediated data store" and "Use version 2 of SMMSTORE API"
```

```
Security ->
Trusted Platform Module ->
Check "TPM 2.0"
```

```
Console ->
Check "Serial port console output" (leave default address and baud rate)
Check "Send console output to a CBMEM buffer"
Default console log level (4: WARNING) (higher loglevel will slowdown your boot time)
```

```
Payload ->
Payload to add: (edk2 payload)
(https://github.com/ellyq/edk2) URL to git repository for edk2
(origin/uefipayload_2402) Insert a commit's SHA-1 or a branch name

Uncheck "Support PS/2 Keyboards"
Check "Support serial output"
Check "Enable UEFI Secure Boot support"
Add a GOP driver to the Tianocore build (3rdparty/blobs/soc/intel/tgl/IntelGopDriver.efi) GOP driver file
Check "Load OpROMs from PCI-E devices", or:
Set "edk2 additional custom build parameters" to: -D VARIABLE_SUPPORT=SMMSTORE -D LOAD_OPTION_ROMS=TRUE
```

```
Debugging ->
Check "Output verbose CBFS debug messages"
```

Then you can boot with `iomem=relaxed` and simply flash coreboot onto it `flashrom -p internal -w build/coreboot.rom`

It *should* work, but as I mentioned - I haven't tested the latest patch on the actual hardware so give me few days to do so 😄 
You should arm yourself with SPI flasher (like ch341a), RS232 null-modem cable and RS232 to USB adapter just in case. It will allow you to read cbmem over serial if anything goes wrong (as well as spawn Linux TTY on it) and re-flash firmware from another system in case of a brick.

Have fun!

**Comment by sonnius** [comment]
Elly, I followed your instructions, however it seems that the 'IntelGopDriver.efi' is not available.


Loading previous configuration from /root/coreboot/payloads/external/edk2/workspace/ellyq/Conf/BuildEnv.sh
Using EDK2 in-source Basetools
WORKSPACE: /root/coreboot/payloads/external/edk2/workspace
EDK_TOOLS_PATH: /root/coreboot/payloads/external/edk2/workspace/ellyq/BaseTools
CONF_PATH: /root/coreboot/payloads/external/edk2/workspace/ellyq/Conf
EDK2: Building... Build environment: Linux-5.14.0-427.35.1.el9_4.x86_64-x86_64-with-glibc2.34
Build start time: 03:51:24, Sep.21 2024

WORKSPACE        = /root/coreboot/payloads/external/edk2/workspace
PACKAGES_PATH    = /root/coreboot/payloads/external/edk2/workspace/ellyq
EDK_TOOLS_PATH   = /root/coreboot/payloads/external/edk2/workspace/ellyq/BaseTools
CONF_PATH        = /root/coreboot/payloads/external/edk2/workspace/ellyq/Conf
PYTHON_COMMAND   = python3

Processing meta-data .

build.py...
 : error 000E: File/directory not found in workspace
	UefiPayloadPkg/IntelGopDriver.efi is not found in packages path:
	/root/coreboot/payloads/external/edk2/workspace/ellyq


- Failed -
Build end time: 03:51:24, Sep.21 2024
Build total time: 00:00:01

Any pointers would be welcome.

**Comment by JackMyers001** [comment]
@sonnius I ran into the same issue. Here's how I fixed it:

- Backup your `.config` file (i.e. copy to another directory)
- Run `make distclean`
- Restore your `.config` file
- Run `make nconfig` and go to `Payload`
  - Set `Tianocore's EDK II payload` to `Specify your own repository`
- Save and build with `make`

Also, for anyone else trying to build the ROM, you'll need `nasm` and `imagemagick` installed from your package manager. Additioanlly, for every path specified in the `Chipset` section, there _shouldn't_ be `blobs/` at the beginning (i.e. `blobs/mainboard/erying/tgl/fd.bin` should actually be `mainboard/erying/tgl/fd.bin`)

**Comment by sonnius** [comment]
Thank you, that worked!

I had already adjusted the paths you mentioned for chipset, but those are definitely needed.

**Comment by ellyq** [comment]
Right, I forgot to mention that you need IntelGopDriver from MrChromebox's blobs repository :)

https://github.com/MrChromebox/blobs/blob/master/soc/intel/tgl/IntelGopDriver.efi

There's also a weird EDK2 bug where it won't find the file, but if you backup your .config, build coreboot without VBT and GOP, then build it with VBT and GOP, it will build just fine.

This is only necessary if you're planning on using the internal GPU though. If you're using an Nvidia GPU, you'll get video output on external monitor just fine (I'm currently testing it with my colleague's RTX2080Ti and it works).

It doesn't work with AMD cards like my RX7800XT unfortunately, so you'd need serial output.

Other than a bit of wonky USB behaviour I just found today, it seems to be production-ready, with newest coreboot and EDK2 tree

-------- Original Message --------

**Comment by ellyq** [comment]
Quick update: Just found out that EDK2 GOP works with AMD cards... if we build coreboot without ReBAR support, will need to investigate this further

**Comment by sonnius** [comment]
I build and flashed the coreboot.rom image on my motherboard but it doesn't seem to work.

I'm using the polestar G613 PRO with i7-11850H CPU (non ES) and the internal GPU.

There's no HDMI output and when I connect a serial connector to the motherboard (at 115200) I get a line of garbage:

rRgb��J���S����iY~��~nj&Zrj~:&F>~Z2~nZ2zvNjn��>J��rRgb�L�L���)�ى)��3    ���22Rr��Ӳ���$���r�r2����d��r�SRR��ȓ22�Rd�r�I2ғ�>J��

I tried 9600 but that doesn't improve the situation.

While I wait for my ch341a to arrive I have a question:

- Can the ESPI_DBG header be used to connect the programmer?
 
The Flash chip on this motherboard is in a difficult location to use the clips to connect to it.

**Comment by ellyq** [comment]
If you get garbage in the terminal, either your adapter is bad, or you plugged the header in the opposite orientation. Can't think of anything else really, baud rate is 115200 by default.

Here's what you should be getting (it's from old build, but should give you some idea):
https://f.sakamoto.pl/elly/coreboot/cbmem-erying.txt

-------- Original Message --------

**Comment by JackMyers001** [comment]
@ellyq using the Coreboot build settings you provided, is XMP expected to work? I've tested a 2x 8GB 3200 MHz kit as well as a 2x 32GB 3200 MHz kit, and in memtest86+, both are apparently running at 2133 MHz.

Performance aside, I think my 64GB kit _needs_ XMP enabled (at least for the higher voltages?), as the board very rarely boots Linux when using it - usually it tries to boot and restarts or brings me back to the EDK2 boot selection screen. I assume this might be due to the DIMMs being dual-rank? 🤷‍♂️. I have found that the 16GB kit is far, far more stable, and I don't believe I've had any issues loading an OS.

**Comment by ellyq** [comment]
> @ellyq using the Coreboot build settings you provided, is XMP expected to work? I've tested a 2x 8GB 3200 MHz kit as well as a 2x 32GB 3200 MHz kit, and in memtest86+, both are apparently running at 2133 MHz.
> 
> Performance aside, I think my 64GB kit _needs_ XMP enabled (at least for the higher voltages?), as the board very rarely boots Linux when using it - usually it tries to boot and restarts or brings me back to the EDK2 boot selection screen. I assume this might be due to the DIMMs being dual-rank? 🤷‍♂️. I have found that the 16GB kit is far, far more stable, and I don't believe I've had any issues loading an OS.

That it strange, my 2x 16GB sticks are dual-rank and they work just fine (also tested single-rank 2x8GB and it was also fine).
The coreboot itself doesn't have any Kconfigs for XMP (in fact, this is the first mainboard in coreboot tree that even attempts to get XMP working on DDR4), so you need to change this line:
https://github.com/ellyq/coreboot/blob/upstreaming-main/src/mainboard/erying/tgl/romstage_fsp_params.c#L38

Refer to this header file for configuration options:
https://github.com/intel/FSP/blob/master/TigerLakeFspBinPkg/Client/Include/FspmUpd.h#L586-L591
